### PR TITLE
Support more JSON Schema features + Refactor

### PR DESCRIPTION
**Pull request by jonathanjouty**
This is what I've been working on...

This Pull Request is not very polished as it changes some of the output to match what I needed, for example:
```diff
-### `size` (number, required) eg: `33`
+### `size` (number, required)
+
+> ### Example JSON:
+
+```json
+"33"
+```
+
```
To have the example separately is probably good (in my opinion), but the `>` is there due to the fact that I'm using this to generate Slate documentation.

The idea of putting this through is to see if you're interested in the PR.
If you are, then I can clean things up.
If not, I'm happy to use our own fork.

### CODE REVIEW

**Comment by saibotsivad** [comment]
I didn't mean to ignore this--apparently I missed the pull request when it came in. Feel free to ping me [on twitter](https://twitter.com/saibotsivad) next time, if you don't get a response within a day or two.

I'll look over the pull request this weekend. Thanks for all the work you've done!

**Comment by jonathanjouty** [comment]
No worries... will do.

I've been on holiday and haven't had time to polish a few things, I'll be looking at this again over the next 2-3 weeks so there will be more!

**Comment by saibotsivad** [comment]
@jonathanjouty I don't have any time to work on this repo, and I don't think I'll have time to work on it over the next couple months either. I've invited you to be a collaborator on this repo, as a member of an [OPEN Open Source](http://openopensource.org/) project. Please review the ground rules on the OOS site, they're pretty simple and hopefully obvious.

Other than that, some simple notes:

* Be sure to follow [semantic versioning](http://semver.org/) very strictly.
    - Absolutely no breaking changes without a major version bump.
    - It's okay to make major version bumps, but please describe them in your pull request, and lets talk about them first.

I'll try to skim through this pull request and leave notes, but feel free to merge it as soon as you feel like it's ready for release.

Thanks for all the work you've put into this so far!

**Comment by jonathanjouty** [comment]
@saibotsivad Thanks, I'll close this PR as more changes were made and put in a polished and proper one in when it's ready.

**Pull request closed without merging**
