### PR TITLE
Simple CLI

### PR DESCRIPTION
**Pull request by kba**
* CLI that can convert schema to markdown on the command line.
* Updated the README

### CODE REVIEW

**Comment by saibotsivad** [comment]
Oh yeah, I like this idea. I'll merge it here shortly.

**Comment by saibotsivad** [comment]
I won't get to it tonight (merged in some bug fixes) but I should get to it soon.

**Comment by saibotsivad** [comment]
In following the very-small-module practice, I'd actually rather have a seperate module like `json-schema-to-markdown-cli` which has the cli side. Then that cli module can use dependencies like [minimist](https://www.npmjs.com/package/minimist) and those dependencies won't be required for the main module.

**Comment by kba** [comment]
Also good. Ping me when you have such a module, I'll be glad to test/contribute.

**Pull request closed without merging**
